name: 'local-run'
description: 'Run workflow locally'
inputs:
  commands:
    description: 'Commands to run workflow locally'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install virtualenv
      shell: bash

    - name: Create virtual environment
      run: |
        virtualenv ~/.virtualenvs/venv
        source ~/.virtualenvs/venv/bin/activate
      shell: bash

    - name: Run workflow
      run: ${{ inputs.commands }}
      shell: bash

    - name: Remove virtual environment
      run: |
        rm -rf ~/.virtualenvs/venv
      shell: bash
